<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2012-2015 AndrÃ© Bargull
    Alle Rechte vorbehalten / All Rights Reserved.  Use is subject to license terms.

    <https://github.com/anba/es6draft>

-->
<!DOCTYPE excludeList [
  <!ELEMENT excludeList (test)*>
  <!ELEMENT test (#PCDATA)>
  <!ATTLIST test id CDATA #REQUIRED>
]>
<excludeList>
  <!-- Intl.v2 changes (sub-classing) -->
  <test id="10.1.1_1"></test>
  <test id="10.1.2.1_4"></test>
  <test id="10.1.2_a"></test>
  <test id="11.1.1_1"></test>
  <test id="11.1.2.1_4"></test>
  <test id="11.1.2"></test>
  <test id="11.3.2_TRP"></test>
  <test id="12.1.1_1"></test>
  <test id="12.1.2.1_4"></test>
  <test id="12.1.2"></test>

  <!-- Intl.v2 changes -->
  <test id="12.3.3">'timeZone' defaults to host environment timezone, if not specified</test>
</excludeList>
